from .home import *
from .preingresos import *
from .ingresos import *
from .ordenes import *
from .orden_acciones import *
from .ajax import *
from .planillas_entrega import *
from .gestion_ordenes import *
from .ingreso_innova import * 
from .procedimientos import *
from .carga_ordenes_plantilla import *