# Generated by Django 5.2.13 on 2026-07-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Numerador',
                'verbose_name_plural': 'Numeradores',
            },
        ),
        migrations.CreateModel(
            name='OrdenAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('anulada', 'Anulada')], default='pendiente', max_length=30)),
                ('tipo', models.CharField(choices=[('analisis', 'Analisis'), ('consulta', 'Consulta'), ('internacion', 'Internacion'), ('practica', 'Practica'), ('otra', 'Otra')], max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero_cupon', models.TextField(blank=True, max_length=120, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('autorizada', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
                ('fecha_tenencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('numero_afiliado', models.CharField(blank=True, max_length=80, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('episodio', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_probable_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('origen_paciente', models.CharField(choices=[('domicilio', 'Domicilio'), ('guardia', 'Guardia'), ('consultorio', 'Consultorio'), ('derivacion', 'Derivación'), ('otro', 'Otro')], default='domicilio', max_length=30)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('programado', 'Programado')], default='normal', max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=160, null=True)),
                ('contacto_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto_parentesco', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_gestion', 'En gestión'), ('ingresado', 'Ingresado'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado'), ('vencido', 'Vencido')], default='pendiente', max_length=30)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('es_preingreso', models.BooleanField(blank=True, default=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('autorizada', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('honorarios_gastos', models.CharField(blank=True, choices=[('honorarios', 'Honorarios'), ('gastos', 'Gastos'), ('todo', 'Todo')], max_length=30, null=True)),
                ('tipo_honorario', models.CharField(blank=True, choices=[('anestesista', 'Anestesista'), ('ayudante1', 'Ayudante 1'), ('ayudante2', 'Ayudante 2'), ('ayudante3', 'Ayudante 3'), ('especialista', 'Especialista')], max_length=40, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_orden', to='entidades.medico')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='entidades.prestacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
