# Generated by Django 5.2.13 on 2026-04-28 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('matricula', models.CharField(max_length=50)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='gestion.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_probable_ingreso', models.DateField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=250, null=True)),
                ('origen_paciente', models.CharField(choices=[('domicilio', 'Domicilio'), ('guardia', 'Guardia'), ('consultorio', 'Consultorio'), ('derivacion', 'Derivación'), ('otro', 'Otro')], default='domicilio', max_length=30)),
                ('numero_afiliado', models.CharField(blank=True, max_length=80, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=160, null=True)),
                ('contacto_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto_parentesco', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('anulado', 'Anulado')], default='pendiente', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='gestion.medico')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preingresos', to='gestion.obrasocial')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preingresos', to='gestion.paciente')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='gestion.plan')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='gestion.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('internacion', 'Internación'), ('quirurgica', 'Consultorios'), ('otra', 'Otra')], max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('autorizada', models.BooleanField(blank=True, default=False, null=True)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('preingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='gestion.preingreso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('honorarios_gastos', models.CharField(blank=True, choices=[('honorarios', 'Honorarios'), ('gastos', 'Gastos'), ('todo', 'Todo')], max_length=30, null=True)),
                ('tipo_honorario', models.CharField(blank=True, choices=[('especialista', 'Especialista'), ('ayudante', 'Ayudante'), ('anestesista', 'Anestesista')], max_length=40, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_orden', to='gestion.medico')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.ordenautorizacion')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='gestion.prestacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
