# Generated by Django 5.2.13 on 2026-07-03 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0002_initial'),
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_autorizacion', to='entidades.medico'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='medico_tenencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tenencia', to='entidades.medico'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='user_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_anuled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='user_autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_autorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='user_tenencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_tenencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.ordenautorizacion'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='entidades.medico'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preingresos', to='entidades.obrasocial'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preingresos', to='entidades.paciente'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='entidades.plan'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='entidades.servicio'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='hecho por'),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='preingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='gestion.preingreso'),
        ),
    ]
