# Generated by Django 5.2.13 on 2026-04-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preingreso',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='entidades.medico'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_orden', to='entidades.medico'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preingresos', to='entidades.obrasocial'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user_deleted',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user_updated',
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preingresos', to='entidades.paciente'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user_deleted',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user_updated',
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='entidades.plan'),
        ),
        migrations.RemoveField(
            model_name='prestacion',
            name='user_deleted',
        ),
        migrations.RemoveField(
            model_name='prestacion',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='prestacion',
            name='user_updated',
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='entidades.prestacion'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingresos', to='entidades.servicio'),
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='ObraSocial',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Prestacion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
