# Generated by Django 5.2.13 on 2026-05-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_preingreso_medico_alter_detalleorden_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preingreso',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='preingreso',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='preingreso',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('programado', 'Programado')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_gestion', 'En gestión'), ('ingresado', 'Ingresado'), ('anulado', 'Anulado'), ('vencido', 'Vencido')], default='pendiente', max_length=30),
        ),
    ]
