# Generated by Django 5.2.13 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_preingreso_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenautorizacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenautorizacion',
            name='numero_cupon',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='tipo_honorario',
            field=models.CharField(blank=True, choices=[('anestesista', 'Anestesista'), ('ayudante1', 'Ayudante 1'), ('ayudante1', 'Ayudante 2'), ('especialista', 'Especialista')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ordenautorizacion',
            name='tipo',
            field=models.CharField(choices=[('analisis', 'Analisis'), ('consulta', 'Consulta'), ('internacion', 'Internacion'), ('practica', 'Practica'), ('otra', 'Otra')], max_length=50),
        ),
    ]
