# Generated by Django 5.2.13 on 2026-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_ordenautorizacion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='autorizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='tipo_honorario',
            field=models.CharField(blank=True, choices=[('anestesista', 'Anestesista'), ('ayudante1', 'Ayudante 1'), ('ayudante2', 'Ayudante 2'), ('especialista', 'Especialista')], max_length=40, null=True),
        ),
    ]
