# Generated by Django 5.2.13 on 2026-06-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_paciente_genero'),
        ('gestion', '0005_detalleorden_autorizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenautorizacion',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entidades.medico'),
        ),
        migrations.AlterField(
            model_name='preingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_gestion', 'En gestión'), ('ingresado', 'Ingresado'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado'), ('vencido', 'Vencido')], default='pendiente', max_length=30),
        ),
    ]
