# Generated by Django 5.2.13 on 2026-07-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_plan_obra_social'),
        ('gestion', '0005_preingreso_user_egreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('edicion', 'Edición'), ('anulacion', 'Anulación'), ('autorizacion', 'Autorización')], default='edicion', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entidades.medico')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion.ordenautorizacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_historicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacion_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('prestacion_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('honorarios_gastos', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_honorario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historico_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.historicoorden')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
