# Generated by Django 5.2.13 on 2026-07-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='entidades.obrasocial'),
        ),
    ]
