# Generated by Django 5.2.13 on 2026-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_plan_obra_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=30, null=True),
        ),
    ]
