# Generated by Django 5.2.13 on 2026-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_paciente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='firma_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
